package io.zer0.muse.ui.chat

import android.annotation.SuppressLint
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView

/**
 * Card renderer (openhanako show-card-tool.ts + card-guide-tool.ts port).
 *
 * Renders HTML/SVG card content generated by the AI's show_card tool
 * inside a sandboxed WebView within a Material Card.
 */
object CardRenderer {

    private const val CARD_PREFIX = "Card '"
    private const val RENDERED_MARKER = "' rendered (id: "

    /** Check if a tool result contains card content. */
    fun isCardResult(toolResult: String): Boolean {
        return toolResult.startsWith(CARD_PREFIX) && toolResult.contains(RENDERED_MARKER)
    }

    /** Extract card id from tool result. */
    fun extractCardId(toolResult: String): String? {
        if (!isCardResult(toolResult)) return null
        val start = toolResult.indexOf(RENDERED_MARKER) + RENDERED_MARKER.length
        val end = toolResult.indexOf(")", start)
        return if (end > start) toolResult.substring(start, end) else null
    }

    /** Build a full HTML page wrapping the card fragment. */
    fun buildCardHtml(code: String, title: String): String {
        return """
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <style>
                    * { box-sizing: border-box; margin: 0; padding: 0; }
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                        background: transparent;
                        color: #1a1a2e;
                        padding: 16px;
                    }
                    svg { max-width: 100%; height: auto; }
                    table { border-collapse: collapse; width: 100%; }
                    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                    th { background: #f5f5f5; }
                    @media (prefers-color-scheme: dark) {
                        body { color: #e0e0e0; }
                        th { background: #2a2a3e; }
                        th, td { border-color: #444; }
                    }
                </style>
            </head>
            <body>$code</body>
            </html>
        """.trimIndent()
    }

    /**
     * Composable card renderer using WebView.
     *
     * @param htmlCode The HTML/SVG fragment to render
     * @param title Card title for accessibility
     * @param modifier Compose modifier
     */
    @SuppressLint("SetJavaScriptEnabled")
    @Composable
    fun RenderCard(
        htmlCode: String,
        title: String,
        modifier: Modifier = Modifier,
    ) {
        Card(
            modifier = modifier.fillMaxWidth(),
            elevation = CardDefaults.cardElevation(defaultElevation = 2.dp),
            colors = CardDefaults.cardColors(
                containerColor = MaterialTheme.colorScheme.surfaceVariant,
            ),
        ) {
            Text(
                text = title,
                style = MaterialTheme.typography.labelMedium,
                modifier = Modifier,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
            AndroidView(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(300.dp),
                factory = { context ->
                    WebView(context).apply {
                        settings.javaScriptEnabled = false // sandboxed
                        settings.allowFileAccess = false
                        settings.allowContentAccess = false
                        webViewClient = WebViewClient()
                        setBackgroundColor(android.graphics.Color.TRANSPARENT)
                        loadDataWithBaseURL(
                            null,
                            buildCardHtml(htmlCode, title),
                            "text/html",
                            "UTF-8",
                            null,
                        )
                    }
                },
            )
        }
    }
}
